// eslint-disable-next-line import/no-anonymous-default-export
export default {
  'en-US':[
    {
      name: 'Home',
      value: '',
      path: '/index',
      key: 'index',
      current: 'index',
      active: true
    },
    {
      name: 'Products',
      value: 'product',
      key: 'product',
      current: 'product',
    },
    {
      name:  'Games Toys',
      value: '33381771',
      path: '/productList/',
      key: '33381771',
      father_key: 'product',
      current: 'product',
    },
    {
      name: 'Cat Bed',
      value: '12771663',
      path: '/productList/',
      key: '12771663',
      father_key: 'product',
      current: 'product',
    },
    {
      name: 'Cat Furniture & Building',
      value: '97974047',
      path: '/productList/',
      key: '97974047',
      father_key: 'product',
      current: 'product',
    },
    {
      name: 'Food Box',
      value: '18885882',
      path: '/productList/',
      key: '18885882',
      father_key: 'product',
      current: 'product',
    },
    {
      name: 'All Product',
      value: 'all',
      path: '/productList/',
      key: 'all',
      father_key: 'product',
      current: 'product',
    },
    {
      name: 'Band',
      value: '',
      path: '/brand',
      key: 'brand',
      current: 'brand',
    },
    {
      name: 'Factory',
      value: '',
      path: '/about',
      key: 'about',
      current: 'about',
    }
  ],
  'ja-JP':[
    {
      name: '表紙',
      value: '',
      path: '/index',
      key: 'index',
      current: 'index',
      active: true
    },
    {
      name: '製品',
      value: 'product',
      key: 'product',
      current: 'product',
    },
    {
      name:  'ゲームのおもちゃ',
      value: '33381771',
      path: '/productList/',
      key: '33381771',
      father_key: 'product',
      current: 'product',
    },
    {
      name: '猫の巣',
      value: '12771663',
      path: '/productList/',
      key: '12771663',
      father_key: 'product',
      current: 'product',
    },
    {
      name: '猫の家具と建物',
      value: '97974047',
      path: '/productList/',
      key: '97974047',
      father_key: 'product',
      current: 'product',
    },
    {
      name: 'フードボックス',
      value: '18885882',
      path: '/productList/',
      key: '18885882',
      father_key: 'product',
      current: 'product',
    },
    {
      name: 'All Product',
      value: 'all',
      path: '/productList/',
      key: 'all',
      father_key: 'product',
      current: 'product',
    },
    {
      name: 'ブランド',
      value: '',
      path: '/brand',
      key: 'brand',
      current: 'brand',
    },
    {
      name: '工場',
      value: '',
      path: '/about',
      key: 'about',
      current: 'about',
    }
  ],
  'zh-CN':[
    {
      name: '首页',
      value: '',
      path: '/index',
      key: 'index',
      current: 'index',
      active: true
    },
    {
      name: '产品',
      value: 'product',
      key: 'product',
      current: 'product',
    },
    {
      name:  '游戏玩具',
      value: '33381771',
      path: '/productList/',
      key: '33381771',
      father_key: 'product',
      current: 'product',
    },
    {
      name: '猫窝',
      value: '12771663',
      path: '/productList/',
      key: '12771663',
      father_key: 'product',
      current: 'product',
    },
    {
      name: '猫家具&拼搭',
      value: '97974047',
      path: '/productList/',
      key: '97974047',
      father_key: 'product',
      current: 'product',
    },
    {
      name: '食盒',
      value: '18885882',
      path: '/productList/',
      key: '18885882',
      father_key: 'product',
      current: 'product',
    },
    {
      name: '所有商品',
      value: 'all',
      path: '/productList/',
      key: 'all',
      father_key: 'product',
      current: 'product',
    },
    {
      name: '品牌',
      value: '',
      path: '/brand',
      key: 'brand',
      current: 'brand',
    },
    {
      name: '工厂',
      value: '',
      path: '/about',
      key: 'about',
      current: 'about',
    }
  ],
};